Upgrade GCC 4.8 image to Python 3.6
This allows upgrading to the latest version of Sphinx, which dropped Python 3.4 compatibility in 2.x. Newer versions of Sphinx hopefully resolve the intermittent docs build failures we see specific to this image, e.g. in https://buildmaster.lubar.me/applications/3/builds/build?buildId=9704

```
FAILED: cd /home/buildmaster/work/_E0/build32-4.8 && /usr/local/bin/sphinx-build -a -E -q -b html /home/buildmaster/work/_E0/src /home/buildmaster/work/_E0/src/docs/html -w /home/buildmaster/work/_E0/src/docs/_sphinx-warnings.txt -j 2

Sphinx parallel build error:
RuntimeError: maximum recursion depth exceeded while pickling an object
```